on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: nflscraper.azurecr.io
        username: ${{ secrets.acr_nflscraper_username }}
        password: ${{ secrets.acr_nflscraper_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t nflscraper.azurecr.io/devcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push nflscraper.azurecr.io/devcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_devcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep streamlit-nfl-scraper | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace streamlit-nfl-scraper`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: streamlit-nfl-scraper
        container-registry-url: nflscraper.azurecr.io
        container-registry-username: ${{ secrets.acr_nflscraper_username }}
        container-registry-password: ${{ secrets.acr_nflscraper_password }}
        secret-name: devclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: streamlit-nfl-scraper
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          nflscraper.azurecr.io/devcluster:${{ github.sha }}
        imagepullsecrets: |
          devclusterdockerauth
